apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: 697786627297.dkr.ecr.us-east-1.amazonaws.com/simplebank:55866afe74bd87579550e5053d456d697e9658ee
          ports:
            - containerPort: 8080
